### ISSUE TITLE
Remove SendmailModule config from Config.pm

### ISSUE THREAD

**Issue by schadom** [juanluisbaptiste/docker-otrs#42] opened 2018-10-07 14:09 UTC
Currently the default Config.pm shipped with docker-otrs locks the following OTRS vars:

    $Self->{'SendmailModule'} = 'Kernel::System::Email::SMTP';
    $Self->{'SendmailModule::Host'} = 'postfix';
    $Self->{'SendmailModule::Port'} = '25';

This makes it impossible to use eg. `Kernel::System::Email::SMTPTLS` as SendmailModule or a custom `SendmailModule::Host ` or `SendmailModule::Port`, as params set in Config.pm have priority over parameters set within the OTRS sysconfig (DB).

Some possible solutions:

1) Do not add static default values via Config.pm for SendmailModule
2) Env variable to disable the inclusion of the default SendmailModule config for the container (eg. OTRS_SENDMAIL_DEFAULT=OFF)
3) Ability to configure all the SendMailModule parameters via container env variables

Thanks

**Comment by juanluisbaptiste** [comment] 2018-10-08 02:32
Hi,

currently I have other tasks to do, PR is welcome.

**Comment by juanluisbaptiste** [comment] 2018-10-08 02:35
Closing this, this is a duplicate of #34 , you had already reported this.

**Closed by juanluisbaptiste** 2018-10-08 02:35 UTC
Labels: enhancement
