### ISSUE TITLE
How to update? (OTRS 5s Patch Level 17)

### ISSUE THREAD

**Issue by drahkrub** [juanluisbaptiste/docker-otrs#11] opened 2017-03-14 11:55 UTC
First: I'm a docker newbie...

What I've done: Stopped all containers (3), pulled new images with docker-compose (found newer images juanluisbaptiste/otrs and juanluisbaptiste/otrs-mariadb), removed the corresponding containers, restarted all with docker-compose.

What happened: Startup looks ok, but `http://$OTRS_HOSTNAME` says "can't connect to mysql on 127.0.0.1". Due to panicking I can't remember my next steps exactly, but I've tried different things, the last one gives a 500/403 right away when going to `http://$OTRS_HOSTNAME`, something I found in `/var/log/httpd/error.log`:

```
[Tue Mar 14 11:53:20 2017] [error] [client 192.168.1.7] Directory index forbidden by Options directive: /var/www/html/
[Tue Mar 14 11:53:20 2017] -e: DBI connect('database=otrs;host=127.0.0.1;','otrs',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/sbin/../../Kernel/System/DB.pm line 202
ERROR: OTRS-CGI-98 Perl: 5.10.1 OS: linux Time: Tue Mar 14 11:53:20 2017

 Message: Can't connect to MySQL server on '127.0.0.1' (111)

 RemoteAddress: 192.168.1.7
 RequestURI: /

 Traceback (67): 
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 164
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 40
   Module: (eval) (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 170
   Module: ModPerl::Registry::handler (v1.99) Line: 31

[Tue Mar 14 11:53:20 2017] -e: DBI connect('database=otrs;host=127.0.0.1;','otrs',...) failed: Can't connect to MySQL server on '127.0.0.1' (111) at /usr/sbin/../../Kernel/System/DB.pm line 202
ERROR: OTRS-CGI-98 Perl: 5.10.1 OS: linux Time: Tue Mar 14 11:53:20 2017

 Message: Can't connect to MySQL server on '127.0.0.1' (111)

 RemoteAddress: 192.168.1.7
 RequestURI: /

 Traceback (67): 
   Module: Kernel::System::DB::Prepare Line: 666
   Module: Kernel::System::Package::RepositoryList Line: 170
   Module: Kernel::System::OTRSBusiness::_GetOTRSBusinessPackageFromRepository Line: 909
   Module: Kernel::System::OTRSBusiness::OTRSBusinessIsInstalled Line: 113
   Module: Kernel::Output::HTML::Layout::Error Line: 1030
   Module: Kernel::Output::HTML::Layout::FatalError Line: 942
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 169
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 40
   Module: (eval) (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 170
   Module: ModPerl::Registry::handler (v1.99) Line: 31

[Tue Mar 14 11:53:21 2017] [error] Can't call method "fetchrow_array" on an undefined value at /usr/sbin/../../Kernel/System/DB.pm line 746.\n
```
What I've done next: Started with an empty `./volumes/config` directory, keeping the stuff in `./volumes/mysql` - now everything is working again, but I've lost several (all) things I've changed via Admin -> SysConfig previously, I think.

Some documentation regarding updates would be nice!

**Comment by drahkrub** [comment] 2017-03-14 12:00
Maybe it's similiar to issue #10 ?!

**Comment by juanluisbaptiste** [comment] 2017-03-14 13:15
Yes, it seems there's an issue detecting the current host volume for the configuration. If you stumble with this again please run the container with OTRS_DEBUG=true and post the output.

**Comment by juanluisbaptiste** [comment] 2017-03-14 13:15
But the upgrade of minor versions should be as simple as pulling the new images and restarting the containers.

**Comment by juanluisbaptiste** [comment] 2017-03-21 15:09
Closing as duplicate of issue #10 (working on it).

**Closed by juanluisbaptiste** 2017-03-21 15:09 UTC
